### ISSUE TITLE
Numeric keypad is not working

### ISSUE THREAD

**Issue by MKappo** [micheldpcarlos/PayoBR#1]
**Steps** 

1.  Click on PayBR extension icon on chrome browser
2.  Click on 'Amount'' field and try to type any number using the Numeric keypad

**Expected Behavior** 

- Numeric keypad should works

**Current Behavior**

- Numeric keypad does not works

**Comment by micheldpcarlos** [comment]
Not reproducible in MacOs, might be related to keyCode in Windows OS

**Comment by thiagoao** [comment]
Same issue here and using Windows 10 pro

**Comment by MKappo** [comment]
> Not reproducible in MacOs, might be related to keyCode in Windows OS

Not sure, cause the issue is reproducible on Linux Ubuntu 18.04

**Comment by micheldpcarlos** [comment]
Marked as Bug, needs review on the function that filter key inputs

**Comment by micheldpcarlos** [comment]
Key validation method replaced with a more compatible one

**Comment by MKappo** [comment]
Fixed confirmed on version **1.1**
