### ISSUE TITLE
Include the USD exchange rate and Payoneer exchange rate over the icon

### ISSUE THREAD

**Issue by jefersonralmeida** [micheldpcarlos/PayoBR#2]
Include the rates on the icon, so the user doesn't have to click on the icon to see it. It can be updated time by time, like every 5 minutes.

**Comment by micheldpcarlos** [comment]
Dollar rate included as a badge text in the icon, this badge is limited to one liner short text, updated every 30s


PR: https://github.com/micheldpcarlos/PayoBR/pull/3
